In [1]:
print(boston.DESCR)

NameError: name 'boston' is not defined

In [2]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:,]
b = y[:]

In [3]:
w, resid, rank, s = np.linalg.lstsq(A, b)
w

array([ -9.16297843e-02,   4.86751203e-02,  -3.77930006e-03,
         2.85636751e+00,  -2.88077933e+00,   5.92521432e+00,
        -7.22447929e-03,  -9.67995240e-01,   1.70443393e-01,
        -9.38925373e-03,  -3.92425680e-01,   1.49832102e-02,
        -4.16972624e-01])

In [4]:
resid

array([ 12231.2173457])

In [26]:
X = pd.DataFrame(w)

In [28]:
X.rename(columns={0: 'weighted value'}, 
         index={0: 'CRIM', 1: 'ZN', 2: 'INDUS', 3: 'CHAS', 4: 'NOX'})

weighted value
CRIM        -0.091630
ZN           0.048675
INDUS       -0.003779
CHAS         2.856368
NOX         -2.880779
5            5.925214
6           -0.007224
7           -0.967995
8            0.170443
9           -0.009389
10          -0.392426
11           0.014983
12          -0.416973

0
CRIM -0.091630
ZN    0.048675
2    -0.003779
3     2.856368
4    -2.880779
5     5.925214
6    -0.007224
7    -0.967995
8     0.170443
9    -0.009389
10   -0.392426
11    0.014983
12   -0.416973

- data
- target
- feature_names
- target_names
- DESCR

In [5]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'],
      dtype='<U7')

In [7]:
boston.target

array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,
        18.9,  15. ,  18.9,  21.7,  20.4,  18.2,  19.9,  23.1,  17.5,
        20.2,  18.2,  13.6,  19.6,  15.2,  14.5,  15.6,  13.9,  16.6,
        14.8,  18.4,  21. ,  12.7,  14.5,  13.2,  13.1,  13.5,  18.9,
        20. ,  21. ,  24.7,  30.8,  34.9,  26.6,  25.3,  24.7,  21.2,
        19.3,  20. ,  16.6,  14.4,  19.4,  19.7,  20.5,  25. ,  23.4,
        18.9,  35.4,  24.7,  31.6,  23.3,  19.6,  18.7,  16. ,  22.2,
        25. ,  33. ,  23.5,  19.4,  22. ,  17.4,  20.9,  24.2,  21.7,
        22.8,  23.4,  24.1,  21.4,  20. ,  20.8,  21.2,  20.3,  28. ,
        23.9,  24.8,  22.9,  23.9,  26.6,  22.5,  22.2,  23.6,  28.7,
        22.6,  22. ,  22.9,  25. ,  20.6,  28.4,  21.4,  38.7,  43.8,
        33.2,  27.5,  26.5,  18.6,  19.3,  20.1,  19.5,  19.5,  20.4,
        19.8,  19.4,  21.7,  22.8,  18.8,  18.7,  18.5,  18.3,  21.2,
        19.2,  20.4,  19.3,  22. ,  20.3,  20.5,  17.3,  18.8,  21.4,
        15.7,  16.2,