문장 내 인라인 수식은 달러 하나 $\alpha^{\beta}가 됩니다.

$$ \alpha = \begin{bmatrix} a & b \\ c & d \end{bmatrix} $$

In [2]:
import numpy as np
import scipy as sp
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms
import sklearn as sk
from tqdm import tqdm_notebook

import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pylab as plt
from mpl_toolkits.mplot3d import Axes3D

import seaborn as sns
sns.set()
sns.set_style("whitegrid")
sns.set_color_codes()

%matplotlib inline
%config InlineBackend.figure_formats = {‘png’, ‘retina’}

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


SyntaxError: invalid character in identifier (<string>, line 1)

### Norm

In [ ]:
A = (np.arange(9) - 4).reshape((3, 3))
A

In [ ]:
np.linalg.norm(A)

### Trance

In [ ]:
np.trace(np.eye(3))

In [ ]:
# 연습문제 2

A = np.array([[1, 2], [2, 3]])
x = np.array([5, 6])

# trace trick

a = np.dot(x.T, A)
b = np.dot(A, x)
a

In [ ]:
np.trace(A)

### Determinant

In [ ]:
A = np.array([[5, 6], [7, 8]])
A

In [ ]:
np.linalg.det(A)

### 역행렬

In [3]:
A = np.array([[2, 3, -2], [3, 5, 6], [2, 4, 3]])
A

array([[ 2,  3, -2],
       [ 3,  5,  6],
       [ 2,  4,  3]])

In [4]:
b = np.array ([[-5], [12], [7]])
b

array([[-5],
       [12],
       [ 7]])

In [5]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0.69230769,  1.30769231, -2.15384615],
       [-0.23076923, -0.76923077,  1.38461538],
       [-0.15384615,  0.15384615, -0.07692308]])

In [6]:
x = np.dot(Ainv, b)
x

array([[-2.84615385],
       [ 1.61538462],
       [ 2.07692308]])

In [7]:
np.dot(A, x)

array([[ -5.],
       [ 12.],
       [  7.]])

In [8]:
s = np.linalg.lstsq(A, b)
s

(array([[-2.84615385],
        [ 1.61538462],
        [ 2.07692308]]),
 array([], dtype=float64),
 3,
 array([ 10.00338293,   3.97814194,   0.32667521]))

### Exercise

In [54]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:,]
b = y[:]

In [55]:
w, resid, rank, s = np.linalg.lstsq(A, b)
w

array([ -9.16297843e-02,   4.86751203e-02,  -3.77930006e-03,
         2.85636751e+00,  -2.88077933e+00,   5.92521432e+00,
        -7.22447929e-03,  -9.67995240e-01,   1.70443393e-01,
        -9.38925373e-03,  -3.92425680e-01,   1.49832102e-02,
        -4.16972624e-01])

In [57]:
resid

array([ 12231.2173457])

In [23]:
A = np.array([[2, 3, -2], [3, 5, 6], [2, 4, 3], [0, 1, 2]])
A

array([[ 2,  3, -2],
       [ 3,  5,  6],
       [ 2,  4,  3],
       [ 0,  1,  2]])

In [24]:
b = np.array([[-5], [12], [7], [6]])
b

array([[-5],
       [12],
       [ 7],
       [ 6]])

In [25]:
Apinv = np.dot(np.linalg.inv(np.dot(A.T, A)), A.T)
Apinv

array([[ 0.04509804,  0.75294118, -0.6745098 , -1.20196078],
       [ 0.15882353, -0.43529412,  0.49411765,  0.72352941],
       [-0.16862745,  0.14117647, -0.04313725, -0.02745098]])

In [26]:
x = np.dot(Apinv, b)
x

array([[-3.12352941],
       [ 1.78235294],
       [ 2.07058824]])

In [27]:
np.dot(A, x)

array([[ -5.04117647],
       [ 11.96470588],
       [  7.09411765],
       [  5.92352941]])

In [28]:
# 한번에 구하는 lstsq
# resid = 잔차

x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([[-3.12352941],
       [ 1.78235294],
       [ 2.07058824]])

In [29]:
resid, np.linalg.norm(np.dot(A, x) - b) ** 2

(array([ 0.01764706]), 0.017647058823529353)