In [1]:
import sympy

sympy.init_printing(use_latex='mathjax')

In [2]:
import scipy as sp

In [3]:
def f2(x):
    return (1 - x[0])**2 + 100.0 * (x[1] - x[0]**2)**2

In [82]:
result = sp.optimize.minimize(f2, (-2, -2))
print(result)
x0 = result['x']
x0

      fun: 1.2197702024999478e-11
 hess_inv: array([[ 0.50957143,  1.01994476],
       [ 1.01994476,  2.04656074]])
      jac: array([  9.66714798e-05,  -4.64005023e-05])
  message: 'Desired error not necessarily achieved due to precision loss.'
     nfev: 496
      nit: 57
     njev: 121
   status: 2
  success: False
        x: array([ 0.99999746,  0.99999468])


array([ 0.99999746,  0.99999468])

In [ ]:
def f2g(x):
    """gradient of f2(x)"""
    return np.array((2.0 * (x[0] - 1) - 400.0 * x[0] * (x[1] - x[0]**2), 200.0 * (x[1] - x[0]**2)))

In [81]:
result = sp.optimize.minimize(f2, (-2, -2), jac=f2g)
print(result)
x0 = result['x']
x0

      fun: 1.1490356198637715e-16
 hess_inv: array([[ 0.49933682,  0.99872978],
       [ 0.99872978,  2.00252814]])
      jac: array([  4.29304940e-07,  -2.14157247e-07])
  message: 'Optimization terminated successfully.'
     nfev: 73
      nit: 56
     njev: 73
   status: 0
  success: True
        x: array([ 1.,  1.])


array([ 1.,  1.])

In [83]:
result = sp.optimize.minimize(f2, (2, 2), jac=f2g)
print(result)
x0 = result['x']
x0

      fun: 3.271435067604758e-14
 hess_inv: array([[ 0.51671918,  1.03179112],
       [ 1.03179112,  2.06544014]])
      jac: array([  5.26067293e-06,  -2.49959031e-06])
  message: 'Optimization terminated successfully.'
     nfev: 35
      nit: 30
     njev: 35
   status: 0
  success: True
        x: array([ 1.00000013,  1.00000025])


array([ 1.00000013,  1.00000025])

In [4]:
x, y = sympy.symbols('x y')
f = (1 - y**2 + 100 * (y - x**2)**2)
f

                     2    
   2       ⎛   2    ⎞     
- y  + 100⋅⎝- x  + y⎠  + 1

In [69]:
y0 = (sympy.diff(f, x))
y1 = (sympy.diff(f, y))
y0, y1

⎛       ⎛   2    ⎞         2        ⎞
⎝-400⋅x⋅⎝- x  + y⎠, - 200⋅x  + 198⋅y⎠

In [86]:
def f2():
    return np.array[[(−400) * x * (−x**2 + y)], [−200 * x**2 + 198 * y]]

SyntaxError: invalid character in identifier (<ipython-input-86-0069cd4e4893>, line 2)

In [59]:
def f2(y0, y1):
    return np.array[[y0, y1]]

In [60]:
result = sp.optimize.minimize(f2, x0, jac=f2)
print(result)
x0 = result['x']
x0

TypeError: f2() missing 1 required positional argument: 'y1'

In [87]:
# fmin_slsqp : squential least square quatratic 

def f1logs(x):
    return np.log(x[0]) + np.log(x[1])

def eq_constraint(x):      # 제한조건
    return x[0] + x[1] - 1

sp.optimize.fmin_slsqp(f1logs, np.array([1, 1]), eqcons=[eq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: -1.3862943611198901
            Iterations: 2
            Function evaluations: 8
            Gradient evaluations: 2


array([ 0.5,  0.5])

In [93]:
def f2(x):
    return np.sqrt((x[0] - 3) ** 2 + (x[1] - 2) ** 2)

def ieq_constraint(x):
    return np.atleast_1d(1 - np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0, 0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 2.8284271248160078
            Iterations: 12
            Function evaluations: 61
            Gradient evaluations: 12


array([  9.99985947e-01,   1.40526578e-05])

In [99]:
def f2(x):
    return np.sqrt((x[0] - 3) ** 2 + (x[1] - 2) ** 2)

def ieq_constraint(x):
    return np.atleast_1d(8 - np.sum(np.abs(x)))

sp.optimize.fmin_slsqp(f2, np.array([0, 0]), ieqcons=[ieq_constraint])

Optimization terminated successfully.    (Exit mode 0)
            Current function value: 7.130469782291134e-07
            Iterations: 18
            Function evaluations: 92
            Gradient evaluations: 18


array([ 3.00000045,  1.99999944])